deploy

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -12,16 +12,29 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v4
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build the Docker image
-        run: docker build -t imagename:tagname .
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-image-name:latest
 
-      - name: Run Docker container
-        run: docker run -d -p 4000:4000 --name containername imagename:tagname
+      # - name: Set up Docker Buildx
+      #   uses: docker/setup-buildx-action@v3
 
-      - name: Check if server is running
-        run: |
-          sleep 5
-          curl --fail http://localhost:4000 || (docker logs containername && exit 1)
+      # - name: Build the Docker image
+      #   run: docker build -t imagename:tagname .
+
+      # - name: Run Docker container
+      #   run: docker run -d -p 4000:4000 --name containername imagename:tagname
+
+      # - name: Check if server is running
+      #   run: |
+      #     sleep 5
+      #     curl --fail http://localhost:4000 || (docker logs containername && exit 1)
